<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## **Define the Following**:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### **Input Layer**:

The input layer receives input from the dataset(s). The input layer is also called the "visible layer" because its the only part that is exposed to and interacts with the data directly. 

### **Hidden Layer**: 

They're hidden in the sense that we don't know what their current state is, and their values are neither input nor output data. They're intermediate states of NN computation.

### **Output Layer**:

Output layers return a vector of values in a suitable format for the problem domain. Typically output values are modified by an activation function to transform it to said suitable format. 

### **Neuron**:

A neuron takes each of the input values, multiplies each of them by a weight, sums the products, and then passes the sum through an activation function which produces the final value.


### **Weight**:


### **Activation Function**:


### **Node Map**:

A node map is a visual diagram of the acrchitecture or "topology" of the neural network. It is somewhat like a flow chart from the input layer to the output layer.

### **Perceptron**:


## Inputs -> Outputs

### **Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?**

First, training data and a sigmoid activation function are required for the neural network before any training or prediction can begin. Firstly one needs to initialize the weights of the intputs with random values, and then calculate the sum of the product of the inputs and weights. The output of this calculation is the _activated value for the end of the first training epoch_. Next, calculate the error by subtracting the activated output from the true values. Use this error matrix to calculate gradient descent/backpropagation. Finally, update the weights matrix by taking the dot product of the inputs and the weights matrix post-backprop.

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
# Imports
import numpy as np

In [2]:
# Sigmoid "activation" function and sigmoid derivative "update" function
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [5]:
# Initialize inputs and weights
np.random.seed(42)
X = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,1]])
y = [[1],[1],[1],[0]]

weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [6]:
# Calculate sum of weighted inputs
weighted_sum = np.dot(X, weights)

# Output activation values for training epoch #1
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.61395979],
       [0.55306642],
       [0.79663861],
       [0.75296649]])

In [7]:
# Calculate error and perform gradient descent/backprop
error = y - activated_output

adjustments = error * sigmoid_derivative(activated_output)
weights += np.dot(X.T, adjustments)

In [8]:
# Loop for 10,000 epochs
for iteration in range(10_000):
    # Weighted sum of inputs
    weighted_sum = np.dot(X, weights)
    
    # Activated weighted sums
    activated_output = sigmoid(weighted_sum)
    
    # Calculate error
    error = y - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update weights
    weights += np.dot(X.T, adjustments)

print("Weights after training: ")
print(weights)

print("Output after training: :")
print(activated_output)

Weights after training: 
[[-11.83951525]
 [-11.83951525]
 [ 17.80813756]]
Output after training: :
[[0.99999998]
 [0.99744851]
 [0.99744851]
 [0.0028127 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [9]:
# Imports
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
# Read data for the two-class version of the Iris dataset
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv')\
       .drop(columns='Id')
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# OOP Perceptron implementation
# Source: https://natureofcode.com/book/chapter-10-neural-networks/
class Perceptron(object):
    def self.__init__(self, learning_rate=0.01, n_iter=1000):
        self.learning_rate = learning_rate
        self.n_iter = n_iter
    
    

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?